name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: upptime/uptime-monitor@v1.39.0
        with:
          command: site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/status-page/__sapper__/export
          cname: status.cocorridor.fr
